= Modern Cpp Örnekleri

Bu depo Tasarım Örüntüleri dersinde gösterilen örnekleri içermektedir.

== Hafta-01

* *Vector*
    
Modern Cpp'ta vector tanımı nedir, nasıl kullanılır sorularını cevaplayan örnektir. Vector değişkeni ile ilgili temel bilgiler anlatılmaktadır.    
    
* *Chat*

Modern Cpp'ta sınıf oluşturmanın mantığını gösteren örnektir. Sınıfları oluştururken nelere dikkat edilmeli, Cpp'ta derleme işlemi nasıl yapılır sorularını cevaplamaya yöneliktir. 

* *Animals*

Ders boyunca yapılacak işlenecek konulara bir örnektir. Private, public sınıfların neler olduğu gösterilmektedir.

== Hafta-02

* *Virtual Functions*

Modern Cpp'ta virtual function (sanal fonksiyon) tanımının ne işe yaradığını, nasıl kullanıldığını anlatan örnektir.

* *Pure Virtual Functions*

Modern Cpp'ta pure virtual function (saf sanal fonksiyon) tanımının ne işe yaradığını, nasıl kullanıldığını ve sanal fonksiyon tanımından farkını gösteren örnektir.

* *Abstract*

Pure virual function'ları (saf sanal fonksiyonları) kullanarak basit bir Abstract sınıf oluşturma örneğidir.

* *Templates*

Modern Cpp'ta template tanımını kısaca anlatan, ne işe yaradığını gösteren örnektir.

* *Move Semantics*

Modern Cpp'ta move() fonksiyonun ne iş yaptığını, rvalue tanımını, lvalue tanımını, && operatörünü gösteren örnektir.

* *Shared Pointer*

Modern Cpp'ta shared pointer (paylaşılan işaretçi) tanımını gösteren ve nasıl kullanıldığını anlatan örnektir.

== Hafta-03

* *Map*

* *Single Responsibility Principle*